dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Nia1UPLdM3TEhyE6KjarqsmiKLMafaTzF+BxYo4spFkxtvsMPRT2kKCsXErkeC/W2sl7fPCI7M8xX9w7/FPGKiivP2vjdA9OGtPZzdLN9Uifc0Fxwlodzlb8kH6TJ/Wwo3kaH5KvHT9mbNdIfgl5rmGxQDHohWqWLLGCm8QUFyp9n+3mtfKHxrueSHIH7veqFGHc4rrK4YMcwFv8Lae3ql8gsOEDwpHdeXFOJF2d2cNj0SB2OMYME1IQWf5KoP+wzobWtyFTFQcnhT4H9ZvgBkEwyvA9zE/S578kiixWsTK8NZDo1HKjBg1m3Gpx1mO8ZKnd2y2QWuqjXLCa2ay6CxCrbRbdlQ97VMIM6R2E6dlufNRMGsV8ym31+09LI1sTotbEDfC4U4koCQW+U7aXVZKIMqYKP0kKqh5a1BIjq24fJQcjU4Y5SiFCle0d5Vb4oiytzMcrw/LktmFgU67NvUGBRbglanpe8vJR7HDsggFWGmjnymWQRjCY9O3abV4pF1rUPPu7BQf+ckQXB8YqBpfjSfmzTnlzQiHXcKQ3TIayM5pMuNm2v7I/oT+dzMoE/0BI9zA6vUNP+R7T2B0JO1H0XRaTZQ+TjJpoCCItF+QTOzzBf0ED7KN8RwFQzS8d+RKJ8oEkc+Y7VE6Msyy98Ennr40l55iIonhwBImWWHo=
