comment:
  image:
    repository: 4babuskin/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: 4babuskin/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: 4babuskin/ui
    tag: latest
    service:
      externalPort: 9292
