global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vladimir_babushkin'
