global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vladimir_babushkin'
