- name: Install Docker
  hosts: all
  become: true
  gather_facts: no
  tags: reddit-app
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

    - name: install additional packages
      apt:
        name: ["apt-transport-https","ca-certificates","curl","gnupg-agent","software-properties-common"]        
        state: present
      become: true

    - name: add key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: add repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker
    
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
