# inventory.compute.gcp.yml
plugin: gcp_compute
projects:
  - docker-239201
zones: # populate inventory with instances in these regions
  - europe-west1-d
filters: []
# A list of options that describe the ordering for which hostnames should be assigned. Currently supported hostnames are 'public_ip', 'private_ip', or 'name'.
# hostnames:
#   - public_ip
#   - name
keyed_groups:
  - key: tags['items']
    separator: ''

scopes:
  - https://www.googleapis.com/auth/gcp-compute
auth_kind: serviceaccount
service_account_file: ../../../../docker-239201-6726f5b2a10f.json
